######################
# 실험 설정
######################
use_wandb: True
exp_name: swin_base_patch4_window12_384
gpus: 0

######################
# 모델 설정
######################
model_type: timm
model_name: swin_base_patch4_window12_384
pretrained: True

######################
# 데이터 설정
######################
train_data_dir: ./data/train_data2_augmentation_motionblur
test_data_dir: ./data/test
base_output_dir: ./result
num_classes: 500
data_name: base
traindata_info_file: ./data/train_data2_augmentation_motionblur.csv
testdata_info_file: ./data/test.csv

######################
# 학습 설정
######################
epochs: 100
learning_rate: 0.0001
num_workers: 8
cos_sch: 50
early_stopping: 10
warm_up: 10
batch_size: 4
weight_decay: 0.0
loss: CE
transform_name: albumentations
optim: AdamW
mixed_precision: True
num_cnn_classes: 20

######################
# 데이터 증강 설정
######################
cutmix_mixup: mixup_cutmix
cutmix_ratio: 0.2
mixup_ratio: 0.2

######################
# 교차 검증 및 기타 설정
######################
n_splits: 5
accumulate_grad_batches: 8
sweep_mode: False
use_kfold: False